# .streamlit/config.toml
[general]
python_version = 3.12 

[server]
# Forzamos que los datos se envíen con codificación segura.
# No siempre soluciona el error en este nivel, pero es buena práctica.
enableCORS = false
